name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Docker Image
      run: docker build -t gcr.io/sinuous-axiom-390804/assignment-frontend:${{ github.sha }} .

    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcp-key.json
        gcloud auth activate-service-account artifact-push@sinuous-axiom-390804.iam.gserviceaccount.com --key-file=/tmp/gcp-key.json
        gcloud --quiet auth configure-docker

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push gcr.io/sinuous-axiom-390804/assignment-frontend:${{ github.sha }}

